name: 'Publish mdbook'
description: 'Publish mdbook to GitHub Pages'
author: 'matthew'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  github_token:
    description: ''
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
